Document `RestClient.request`’s `version` param
ably/sdk-api-reference pull request #32
Opened 2023-05-01 19:04 UTC by lawrence-forooghian

As described by `RSC19f1` in https://github.com/ably/specification/commit/c184af09d0527662bfe153c596681bc00101837f.

2023-05-02 10:59 UTC, owenpearson requested changes
A couple of thoughts:
- I think we could do better than "protocol version" here. I don't expect anyone reading this to be certain of what it means and they'll likely end up at https://www.google.com/search?q=ably+protocol+version which won't help much either. Perhaps something like "major REST API version" would make it more obvious?
- "Any Ably documentation which recommends the use of this method will specify what value to pass for this parameter" really ought to be the case but that's certainly not the case now and it would be a significant task to update all the documentation which uses `Rest.request`. I'd be tempted to just link out to https://ably.com/docs/api/rest-api#versioning instead.

2023-05-02 13:14 UTC, lawrence-forooghian commented
Thanks for the feedback @owenpearson, I’ve changed it based on your feedback. The comment about "Any Ably documentation which recommends the use of this method will specify what value to pass for this parameter" was based on this comment in [ADR61](https://ably.atlassian.net/wiki/spaces/ENG/pages/2222456951/ADR61+Versioning+of+realtime+API+endpoints):

> In all documentation and casual interactions where we recommend to customers that they use rest#request, and tell them what they should expect, we should give them a protocol version to supply.

But from what you're saying, that's more of a that'd-be-great than a we're-planning-on-doing-this, so I’ve removed it.

2023-05-09 15:58 UTC, m-hulbert reviewed
One minor suggestion just to keep the text consistent with the description for `params`.

2023-05-09 15:58 UTC, m-hulbert commented on descriptions.md
> +|| `version` || RSC19f1 | The major version of the Ably REST API to use. For more information about REST API versioning, see [this section of the REST API reference](https://ably.com/docs/api/rest-ap
```suggestion
|| `version` || RSC19f1 | The major version of the Ably REST API to use. See the [REST API reference](https://ably.com/docs/api/rest-api#versioning) for information on versioning. |
```

2023-05-10 16:30 UTC, m-hulbert approved these changes
LGTM

2023-05-10 17:01 UTC, merged